backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "info"
    label: "Info"
    folder: "src/pages/info"
    create: true
    slug: "{{section}}/{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "info-page"}
      - label: "Section"
        name: "section"
        widget: "relation"
        collection: "section"
        displayFields: ["title"]
        searchFields: ["title"]
        valueField: "title"
        required: true
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: Image, name: image, widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Link"
        name: "link"
        widget: "object"
        required: false
        fields:
          - {label: "Link text", name: "linkText", widget: "string", required: false},
          - {label: "Link URL", name: "linkUrl", widget: "string", required: false}

  - name: "section"
    label: "Section Page"
    folder: "src/pages/sections"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "section-page"}
      - {label: Title, name: title, widget: string}
      - {label: Order, name: order, widget: number}
      - {label: "Body", name: "body", widget: "markdown"}
      
      
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/complete/index.md"
        label: "Complete Page"
        name: "complete"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "complete-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}