backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "info"
    label: "Info Pages"
    folder: "src/pages/info"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "info-page"}
      - label: "Section"
        name: "section"
        widget: "relation"
        collection: "section"
        displayFields: ["title"]
        searchFields: ["title"]
        valueField: "title"
        required: true
      - {label: "Title", name: "title", widget: "string"}
      - label: "Background Colour"
        name: "bg"
        widget: "select"
        options:
          - { label: "Bright Green", value: "#00E7C0" }
          - { label: "Light Green", value: "#E2F6F0" }
          - { label: "Bright Blue", value: "#2D7ADE" }
          - { label: "Light Blue", value: "#BEEAF8" }
          - { label: "Pink", value: "#EADDDD" }
          - { label: "Grey", value: "#F8F8F8" }
          - { label: "Yellow", value: "#FDFBE6" }
      - {label: "Order", name: "order", widget: "number"}
      - {label: Image, name: image, widget: image, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Link"
        name: "link"
        widget: "object"
        required: false
        fields:
          - {label: "Link text", name: "linkText", widget: "string", required: false}
          - {label: "Link URL", name: "linkUrl", widget: "string", required: false}

  - name: "section"
    label: "Section Pages"
    folder: "src/pages/sections"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "section-page"}
      - {label: Title, name: title, widget: string}
      - {label: Order, name: order, widget: number}
      - {label: "Body", name: "body", widget: "markdown"}
      
      
  - name: "pages"
    label: "Other Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/get-started/index.md"
        label: "Starting Page"
        name: "starting"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "start-page"}
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/complete/index.md"
        label: "Complete Page"
        name: "complete"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "complete-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}